### ISSUE TITLE
Feature: User can visualyse a base polyhedra

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can visualize a full 3D model of a base polyhedra, in this case an icosidodecahedron (a 32-sided polyhedron formed from 20 regular triangles and 12 regular pentagons, with 30 vertices and 60 edges).

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The main application page will have a header and a HTML `< canvas >` element, inside of which the 3D model will be displayed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-08 at 11 31 25 AM](https://user-images.githubusercontent.com/78445066/172690884-d175ae62-d317-49e4-aa90-b730114de106.png)
![Screen Shot 2022-06-08 at 11 31 37 AM](https://user-images.githubusercontent.com/78445066/172690901-45e164e6-c592-435c-9460-71b835a5504e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to ... the dbdesigner 'The Hedrographer'
- [ ] Update `data.sql` to ... insert the row for the 'Icosidodecahedron' polyhedron.

### ☁️ Server

- [ ] Update `server/index.js` to ... update the data.js from the json column of the database
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client
- [ ] Install the npm THREE.js library
- [ ] Install the npm React-Three/Fiber library

### ⚡ Client

- [ ] Create a header component to showcase the webapp's name
- [ ] Create the HTML skelleton of the webapp.
- [ ] Create the CSS of the app
- [ ] Stylize the header
- [ ] Create a THREE.js component to showcase the polyhedron saved in the data.js
- [ ] 
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
